<a href="https://colab.research.google.com/github/KovryakRuslan312005/MH-Kovryak-Ruslan-3-16/blob/main/%D0%9A%D0%BE%D0%B2%D1%80%D1%8F%D0%BA%20%D0%A0%D1%83%D1%81%D0%BB%D0%B0%D0%BD%20%20%D0%9B%D0%B0%D0%B1%D0%B0%20%E2%84%964.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота №4 Ковряк Руслан Павлович

Крок №1 Імпортуємо бібліотеки

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt


Крок №2 Завантажуємо дані

In [ ]:
data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target)


 Крок №3  Робимо попередній аналіз

In [ ]:
print("Перші 5 рядків:\n", X.head())
print("\nНазви стовпців:\n", X.columns)
print("\nТипи даних:\n", X.dtypes)
print("\nПропущені значення:\n", X.isnull().sum())
print("\nРозмірність:\n", X.shape)


Перші 5 рядків:
    mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimete

Крок №4 Розділення даних(тренувальні та тестові)  

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


Крок №5 Створюємо моделі

In [ ]:
log_reg = LogisticRegression(max_iter=10000)
tree = DecisionTreeClassifier()
forest = RandomForestClassifier()


Крок №6 Підбираємо підходящі параметри  

In [ ]:
log_params = {'C': [0.1, 1, 10]}
tree_params = {'max_depth': [3, 5, 10]}
forest_params = {'n_estimators': [50, 100], 'max_depth': [5, 10]}

log_search = GridSearchCV(log_reg, log_params, cv=5)
tree_search = GridSearchCV(tree, tree_params, cv=5)
forest_search = GridSearchCV(forest, forest_params, cv=5)

log_search.fit(X_train, y_train)
tree_search.fit(X_train, y_train)
forest_search.fit(X_train, y_train)


GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [5, 10], 'n_estimators': [50, 100]})

 Крок №7 Оцінюємо моделі

In [ ]:
models = {
    'Логістична регресія': log_search,
    'Дерево рішень': tree_search,
    'Випадковий ліс': forest_search
}

for name, model in models.items():
    print(f"\n--- {name} ---")
    y_pred = model.predict(X_test)
    print(f"Точність: {accuracy_score(y_test, y_pred):.2f}")
    print("Матриця помилок:")
    print(confusion_matrix(y_test, y_pred))
    print("Звіт про класифікацію:")
    print(classification_report(y_test, y_pred))


--- Логістична регресія ---
Точність: 0.96
Матриця помилок:
[[39  4]
 [ 1 70]]
Звіт про класифікацію:
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114


--- Дерево рішень ---
Точність: 0.95
Матриця помилок:
[[39  4]
 [ 2 69]]
Звіт про класифікацію:
              precision    recall  f1-score   support

           0       0.95      0.91      0.93        43
           1       0.95      0.97      0.96        71

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114


--- Випадковий ліс ---
Точність: 0.96
Матриця помилок:
[[40  3]
 [ 2 69]]
Звіт про класифікацію:
              precision    recall  f1-score   su

Крок №8 Вибір найкращої моделі та прогнозу


In [ ]:
 best_model = max(models.items(), key=lambda x: accuracy_score(y_test, x[1].predict(X_test)))
print(f"\nНайкраща модель: {best_model[0]}")

final_predictions = best_model[1].predict(X_test)
print("\nРезультати прогнозування (перші 10):")
print(final_predictions[:10])



Найкраща модель: Логістична регресія

Результати прогнозування (перші 10):
[1 0 0 1 1 0 0 0 1 1]


Висновок:
Я використовував в цій лабі та дізнався що  таке GridSearchCV(він автоматично
найкращі параметри).Це я дізнався з цієї лаби.
